name: CI

on:
  push:
    branches: [feat/cli-token-auth]
  pull_request:
    branches: [feat/cli-token-auth]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtualenv and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          export PYTHONPATH=src
          pytest tests/

      - name: Lint with Ruff (optional)
        run: |
          source .venv/bin/activate
          ruff check .
